# Generated by Django 2.0.4 on 2018-04-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosted',
            name='two',
            field=models.BooleanField(default=False),
        ),
    ]
