# Generated by Django 2.0.4 on 2018-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_hosted_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosted',
            name='two',
            field=models.IntegerField(default=0),
        ),
    ]
